CREATE DATABASE db_classificado;

USE db_classificado;

CREATE TABLE tb_usuarios(

Id INT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
USUARIO VARCHAR(50) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
PESSOA VARCHAR(255) NOT NULL,
IMAGEM VARCHAR(100) NOT NULL,
);


CREATE TABLE tb_anuncios(

Id INT NOT NULL PRIMARY KEY IDENTITY,
Produto VARCHAR(45) NOT NULL,
Descricao VARCHAR(100) NOT NULL,
Contato VARCHAR NOT NULL,
Imagem VARCHAR (100)NOT NULL,
datas DATE,
Fk_Criador INT NOT NULL,
FOREIGN KEY(Fk_Criador) REFERENCES tb_usuarios(Id),

);


